const dataCollection = [
  {
    banco_tipo: "BP",
    banco_codigo: "0003",
    banco_nombre: "BANCO DE DEPOSITOS, S.A.",
    banco_cif: "A07001027",
    via_tipo: "PS",
    via_nombre: "DE LA CASTELLANA",
    via_numero: 120,
    via_resto: "",
    direccion_cp: "28046",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "914352175",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "5493007LK0D8SKLLH161",
    banco_emails: ["atencionclienteBD@bancodepositos.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0019",
    banco_nombre: "DEUTSCHE BANK, SOCIEDAD ANONIMA ESPAÑOLA",
    banco_cif: "A08000614",
    via_tipo: "PS",
    via_nombre: "DE LA CASTELLANA",
    via_numero: "18",
    via_resto: "",
    direccion_cp: "28046",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "913355800",
    banco_web: "WWW.DEUTSCHE-BANK.ES",
    banco_nombre_comercial: "DB-S.A.E.",
    cod_autonomia: "12",
    cod_lei: "529900SICIK5OVMVY186",
    banco_emails: ["atencion.clientes@db.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0049",
    banco_nombre: "BANCO SANTANDER, S.A.",
    banco_cif: "A39000013",
    via_tipo: "PS",
    via_nombre: "DE PEREDA",
    via_numero: "9-12",
    via_resto: "",
    direccion_cp: "39004",
    direccion_poblacion: "SANTANDER",
    direccion_provincia: "CANTABRIA",
    banco_telefono: "942206100",
    banco_web: "www.santander.com",
    banco_nombre_comercial: "SANTANDER",
    cod_autonomia: "6",
    cod_lei: "5493006QMFDDMYWIAM13",
    banco_emails: ["santander_reclamaciones@gruposantander.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0061",
    banco_nombre: "BANCA MARCH, S.A.",
    banco_cif: "A07004021",
    via_tipo: "AV",
    via_nombre: "ALEJANDRO ROSELLO",
    via_numero: "8",
    via_resto: "",
    direccion_cp: "7002",
    direccion_poblacion: "PALMA",
    direccion_provincia: "ILLES BALEARS",
    banco_telefono: "971779100",
    banco_web: "WWW.BANCAMARCH.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "4",
    cod_lei: "959800LQ598A5RQASA61",
    banco_emails: ["atencion_cliente@bancamarch.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0073",
    banco_nombre: "OPEN BANK, S.A.",
    banco_cif: "A28021079",
    via_tipo: "PZ",
    via_nombre: "SANTA BARBARA",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "28004",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "913421000",
    banco_web: "WWW.OPENBANK.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140006024944",
    banco_emails: ["ayuda@openbank.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0078",
    banco_nombre: "BANCA PUEYO, S.A.",
    banco_cif: "A06001671",
    via_tipo: "CL",
    via_nombre: "NUESTRA SEÑORA DE GUADALUPE",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "6700",
    direccion_poblacion: "VILLANUEVA DE LA SERENA",
    direccion_provincia: "BADAJOZ",
    banco_telefono: "924846008",
    banco_web: "WWW.BANCAPUEYO.ES",
    banco_nombre_comercial: "BANCA PUEYO",
    cod_autonomia: "10",
    cod_lei: "95980020140005487855",
    banco_emails: ["servicioatencioncliente@bancapueyo.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0081",
    banco_nombre: "BANCO DE SABADELL, S.A.",
    banco_cif: "A08000143",
    via_tipo: "AV",
    via_nombre: "OSCAR ESPLA",
    via_numero: "37",
    via_resto: "",
    direccion_cp: "3007",
    direccion_poblacion: "ALICANTE",
    direccion_provincia: "",
    banco_telefono: "937289289",
    banco_web: "WWW.GRUPOBANCOSABADELL.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "SI5RG2M0WQQLZCXKRM20",
    banco_emails: ["SAC@bancsabadell.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0091",
    banco_nombre: "BANCO DE ALBACETE, S.A.",
    banco_cif: "A02000974",
    via_tipo: "AV",
    via_nombre: "DE CANTABRIA",
    via_numero: "S/N",
    via_resto: "CIUDAD GRP.SANTANDER",
    direccion_cp: "28660",
    direccion_poblacion: "BOADILLA DEL MONTE",
    direccion_provincia: "MADRID",
    banco_telefono: "913422881",
    banco_web: "WWW.BANCODEALBACETE.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "959800MZYB6CKWA9K382",
    banco_emails: ["santander_reclamaciones@gruposantander.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0121",
    banco_nombre: "BANCO OCCIDENTAL, S.A.",
    banco_cif: "A28137958",
    via_tipo: "CL",
    via_nombre: "AZUL",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "28050",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "944876571",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140005816006",
    banco_emails: [
      "info@bancooccidentalb.com",
      "diego-lopez@bancooccidentalb.com",
    ],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0128",
    banco_nombre: "BANKINTER, S.A.",
    banco_cif: "A28157360",
    via_tipo: "PS",
    via_nombre: "DE LA CASTELLANA",
    via_numero: "29",
    via_resto: "",
    direccion_cp: "28046",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "913397500",
    banco_web: "WWW.EBANKINTER.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "VWMYAEQSTOPNV0SUGU82",
    banco_emails: ["incidencias_sac.bankinter@bankinter.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0133",
    banco_nombre: "NUEVO MICRO BANK, S.A.",
    banco_cif: "A65619421",
    via_tipo: "CL",
    via_nombre: "ADUANA",
    via_numero: "18",
    via_resto: "",
    direccion_cp: "28013",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "932813750",
    banco_web: "WWW.MICROBANKLACAIXA.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140005635198",
    banco_emails: ["servicio.cliente@caixabank.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0182",
    banco_nombre: "BANCO BILBAO VIZCAYA ARGENTARIA, S.A.",
    banco_cif: "A48265169",
    via_tipo: "PZ",
    via_nombre: "DE SAN NICOLAS",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "48005",
    direccion_poblacion: "BILBAO",
    direccion_provincia: "BIZKAIA",
    banco_telefono: "944876000",
    banco_web: "WWW.BBVA.COM",
    banco_nombre_comercial: "BBVA",
    cod_autonomia: "16",
    cod_lei: "K8MS7FD7N5Z2WQ51AZ71",
    banco_emails: ["reclamacionessac@bbva.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0186",
    banco_nombre: "BANCO MEDIOLANUM, S.A.",
    banco_cif: "A58640582",
    via_tipo: "CL",
    via_nombre: "BARCAS",
    via_numero: "10",
    via_resto: "",
    direccion_cp: "46002",
    direccion_poblacion: "VALENCIA",
    direccion_provincia: "",
    banco_telefono: "932535400",
    banco_web: "WWW.BANCOMEDIOLANUM.ES",
    banco_nombre_comercial: "BANCOMEDIOLANUM",
    cod_autonomia: "15",
    cod_lei: "2138001YBO7CJNQOEE37",
    banco_emails: ["banca.telefonica@mediolanum.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0198",
    banco_nombre: "BANCO COOPERATIVO ESPAÑOL, S.A.",
    banco_cif: "A79496055",
    via_tipo: "CL",
    via_nombre: "VIRGEN DE LOS PELIGROS",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "28013",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "915956700",
    banco_web: "WWW.BANCOCOOPERATIVO.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "549300LYFYVPUCG6SY25",
    banco_emails: ["bancocooperativo.attcliente@cajarural.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0234",
    banco_nombre: "CBNK BANCO DE COLECTIVOS, S.A.",
    banco_cif: "A28520666",
    via_tipo: "CL",
    via_nombre: "ALMAGRO",
    via_numero: "8",
    via_resto: "",
    direccion_cp: "28010",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "913193448",
    banco_web: "WWW.BANCOCAMINOS.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140005772841",
    banco_emails: ["cat-ingenieria@cbnk.es", "cat-salud@cbnk.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0235",
    banco_nombre: "BANCO PICHINCHA ESPAÑA, S.A.",
    banco_cif: "A85882330",
    via_tipo: "CL",
    via_nombre: "LAGASCA",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "28001",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "917818958",
    banco_web: "WWW.BANCOPICHINCHA.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140005952097",
    banco_emails: ["atencionalcliente@bancopichincha.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0237",
    banco_nombre: "CAJASUR BANCO, S.A.",
    banco_cif: "A95622841",
    via_tipo: "AV",
    via_nombre: "GRAN CAPITAN",
    via_numero: "11-13",
    via_resto: "",
    direccion_cp: "14008",
    direccion_poblacion: "CÓRDOBA",
    direccion_provincia: "",
    banco_telefono: "944017000",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005488243",
    banco_emails: ["atencion.cliente@grupokutxabank.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0239",
    banco_nombre: "EVO BANCO S.A.",
    banco_cif: "A70386024",
    via_tipo: "CL",
    via_nombre: "DON RAMÓN DE LA CRUZ",
    via_numero: "84",
    via_resto: "",
    direccion_cp: "28006",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "915866030",
    banco_web: "www.evobanco.com",
    banco_nombre_comercial: "EVO BANCO S.A.",
    cod_autonomia: "12",
    cod_lei: "95980020140005375820",
    banco_emails: ["contactoevo@evobanco.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0243",
    banco_nombre: "CREDIT SUISSE BANK (EUROPE) S.A.",
    banco_cif: "A79192258",
    via_tipo: "CL",
    via_nombre: "AYALA",
    via_numero: "42",
    via_resto: "3 PLANTA B",
    direccion_cp: "28001",
    direccion_poblacion: "MADRID",
    direccion_provincia: "MADRID",
    banco_telefono: "917916000",
    banco_web: "WWW.CREDIT-SUISSE.COM/ES/ES.HTML",
    banco_nombre_comercial: "CREDIT SUISSE BANK EUROPE",
    cod_autonomia: "12",
    cod_lei: "959800TMGPWX7NYM4R72",
    banco_emails: [],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "0244",
    banco_nombre: "MIRALTA FINANCE BANK, S.A.",
    banco_cif: "A06302657",
    via_tipo: "PZ",
    via_nombre: "MANUEL GOMEZ MORENO",
    via_numero: "2",
    via_resto: "17 A",
    direccion_cp: "28020",
    direccion_poblacion: "MADRID",
    direccion_provincia: "MADRID",
    banco_telefono: "917882901",
    banco_web: "WWW.MIRALTABANK.COM",
    banco_nombre_comercial: "MIRALTA",
    cod_autonomia: "12",
    cod_lei: "95980020140005385035",
    banco_emails: ["info@Miraltabank.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "1490",
    banco_nombre: "SINGULAR BANK, S.A.",
    banco_cif: "A85597821",
    via_tipo: "CL",
    via_nombre: "GOYA",
    via_numero: "11",
    via_resto: "",
    direccion_cp: "28001",
    direccion_poblacion: "MADRID",
    direccion_provincia: "MADRID",
    banco_telefono: "917894000",
    banco_web: "WWW.SINGULARBANK.ES",
    banco_nombre_comercial: "SINGULAR BANK",
    cod_autonomia: "12",
    cod_lei: "95980020140005419373",
    banco_emails: ["informacionbp@singularbank.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "1544",
    banco_nombre: "MYINVESTOR BANCO, S.A.",
    banco_cif: "A86701711",
    via_tipo: "PS",
    via_nombre: "DE LA CASTELLANA",
    via_numero: "55",
    via_resto: "PL. 3",
    direccion_cp: "28046",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "912062850",
    banco_web: "WWW.ANDBANK.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "95980020140005310927",
    banco_emails: ["atencion.cliente@myinvestor.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2000",
    banco_nombre: "CECABANK, S.A.",
    banco_cif: "A86436011",
    via_tipo: "CL",
    via_nombre: "ALCALA",
    via_numero: "27",
    via_resto: "",
    direccion_cp: "28014",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "915965000",
    banco_web: "WWW.cecabank.es",
    banco_nombre_comercial: "CECABANK, S.A.",
    cod_autonomia: "12",
    cod_lei: "549300CQ9NLEHMRCU505",
    banco_emails: ["servicioatencionalcliente@cecabank.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2080",
    banco_nombre: "ABANCA CORPORACION BANCARIA, S.A.",
    banco_cif: "A70302039",
    via_tipo: "CL",
    via_nombre: "CANTON CLAUDINO PITA",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "15300",
    direccion_poblacion: "BETANZOS",
    direccion_provincia: "A CORUÑA",
    banco_telefono: "981187000",
    banco_web: "",
    banco_nombre_comercial: "ABANCA CORPORACION BANCAR",
    cod_autonomia: "11",
    cod_lei: "54930056IRBXK0Q1FP96",
    banco_emails: ["atencioncliente@abanca.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2085",
    banco_nombre: "IBERCAJA BANCO, S.A.",
    banco_cif: "A99319030",
    via_tipo: "PZ",
    via_nombre: "BASILIO PARAISO",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "50008",
    direccion_poblacion: "ZARAGOZA",
    direccion_provincia: "",
    banco_telefono: "976767676",
    banco_web: "WWW.IBERCAJA.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "2",
    cod_lei: "549300OLBL49CW8CT155",
    banco_emails: ["atencioncliente@ibercaja.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2095",
    banco_nombre: "KUTXABANK, S.A",
    banco_cif: "A95653077",
    via_tipo: "CL",
    via_nombre: "GRAN VIA",
    via_numero: "30-32",
    via_resto: "",
    direccion_cp: "48009",
    direccion_poblacion: "BILBAO",
    direccion_provincia: "BIZKAIA",
    banco_telefono: "944017526",
    banco_web: "",
    banco_nombre_comercial: "KUTXABANK, S.A",
    cod_autonomia: "16",
    cod_lei: "549300U4LIZV0REEQQ46",
    banco_emails: ["atencion.cliente@grupokutxabank.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2100",
    banco_nombre: "CAIXABANK, S.A.",
    banco_cif: "A08663619",
    via_tipo: "CL",
    via_nombre: "PINTOR SOROLLA",
    via_numero: "2-4",
    via_resto: "",
    direccion_cp: "46002",
    direccion_poblacion: "VALENCIA",
    direccion_provincia: "",
    banco_telefono: "934046000",
    banco_web: "WWW.CAIXABANK.ES",
    banco_nombre_comercial: "CAIXABANK, S.A.",
    cod_autonomia: "15",
    cod_lei: "7CUNS533WID6K7DGFI87",
    banco_emails: ["servicio.cliente@caixabank.com"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "2103",
    banco_nombre: "UNICAJA BANCO, S.A.",
    banco_cif: "A93139053",
    via_tipo: "AV",
    via_nombre: "ANDALUCIA",
    via_numero: "10-12",
    via_resto: "",
    direccion_cp: "29007",
    direccion_poblacion: "MALAGA",
    direccion_provincia: "",
    banco_telefono: "952138000",
    banco_web: "WWW.UNICAJA.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "5493007SJLLCTM6J6M37",
    banco_emails: ["atencion.al.cliente@unicaja.es"],
  },
  {
    banco_tipo: "BP",
    banco_codigo: "3183",
    banco_nombre: "ARQUIA BANK, S.A.",
    banco_cif: "A08809808",
    via_tipo: "CL",
    via_nombre: "TUTOR",
    via_numero: "16",
    via_resto: "",
    direccion_cp: "28008",
    direccion_poblacion: "MADRID",
    direccion_provincia: "",
    banco_telefono: "934826810",
    banco_web: "WWW.ARQUIA.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "12",
    cod_lei: "959800AQXRU3780MW094",
    banco_emails: ["atencionalcliente@arquia.es"],
  },
  {
    banco_tipo: "CA",
    banco_codigo: "2045",
    banco_nombre: "CAJA DE AHORROS Y MONTE DE PIEDAD DE ONTINYENT",
    banco_cif: "G46002796",
    via_tipo: "PZ",
    via_nombre: "SANTO DOMINGO",
    via_numero: "24",
    via_resto: "",
    direccion_cp: "46870",
    direccion_poblacion: "ONTINYENT",
    direccion_provincia: "VALENCIA",
    banco_telefono: "962919100",
    banco_web: "WWW.CAIXAONTINYENT.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005436542",
    banco_emails: ["co@caixaontinyent.es"],
  },
  {
    banco_tipo: "CA",
    banco_codigo: "2056",
    banco_nombre: "COLONYA - CAIXA D'ESTALVIS DE POLLENSA",
    banco_cif: "G07000045",
    via_tipo: "PZ",
    via_nombre: "MAYOR",
    via_numero: "7",
    via_resto: "",
    direccion_cp: "7460",
    direccion_poblacion: "POLLENSA",
    direccion_provincia: "ILLES BALEARS",
    banco_telefono: "971530162",
    banco_web: "WWW.COLONYA.ES",
    banco_nombre_comercial: "COLONYA",
    cod_autonomia: "4",
    cod_lei: "95980020140006025332",
    banco_emails: ["sac@colonya.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3001",
    banco_nombre: "CAJA RURAL DE ALMENDRALEJO, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F06004816",
    via_tipo: "PZ",
    via_nombre: "DE SAN ANTONIO",
    via_numero: "S/N",
    via_resto: "",
    direccion_cp: "6200",
    direccion_poblacion: "ALMENDRALEJO",
    direccion_provincia: "BADAJOZ",
    banco_telefono: "924670371",
    banco_web: "WWW.CAJALMENDRALEJO.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "10",
    cod_lei: "95980020140005937353",
    banco_emails: ["atencioncliente@cajalmendralejo.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3005",
    banco_nombre: "CAJA RURAL CENTRAL, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F03014677",
    via_tipo: "CL",
    via_nombre: "JOSE MARIA SARGET",
    via_numero: "29",
    via_resto: "",
    direccion_cp: "3300",
    direccion_poblacion: "ORIHUELA",
    direccion_provincia: "ALICANTE",
    banco_telefono: "966747800",
    banco_web: "WWW.RURALCENTRAL.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005487079",
    banco_emails: ["atencion_clientes_crcentral@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3007",
    banco_nombre:
      "CAJA RURAL DE GIJON, SOCIEDAD COOPERATIVA ASTURIANA DE CREDITO",
    banco_cif: "F33604455",
    via_tipo: "PS",
    via_nombre: "INFANCIA",
    via_numero: "10",
    via_resto: "",
    direccion_cp: "33207",
    direccion_poblacion: "GIJON",
    direccion_provincia: "ASTURIAS",
    banco_telefono: "985180401",
    banco_web: "WWW.RURALVIA.COM/GIJON",
    banco_nombre_comercial: "",
    cod_autonomia: "3",
    cod_lei: "95980020140005480580",
    banco_emails: ["crgijon.3007@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3008",
    banco_nombre: "CAJA RURAL DE NAVARRA, S. COOP. DE CREDITO",
    banco_cif: "F31021611",
    via_tipo: "PZ",
    via_nombre: "DE LOS FUEROS",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "31003",
    direccion_poblacion: "PAMPLONA",
    direccion_provincia: "NAVARRA",
    banco_telefono: "948168100",
    banco_web: "WWW.RURALVIA.COM/NAVARRA",
    banco_nombre_comercial: "",
    cod_autonomia: "14",
    cod_lei: "95980020140005439549",
    banco_emails: ["info@crnavarra.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3009",
    banco_nombre: "CAJA RURAL DE EXTREMADURA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F06002661",
    via_tipo: "AV",
    via_nombre: "SANTA MARINA",
    via_numero: "15",
    via_resto: "",
    direccion_cp: "6005",
    direccion_poblacion: "BADAJOZ",
    direccion_provincia: "",
    banco_telefono: "924207474",
    banco_web: "WWW.CREXTREMADURA.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "10",
    cod_lei: "95980020140005212375",
    banco_emails: ["atencioncliente@crextremadura.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3016",
    banco_nombre: "CAJA RURAL DE SALAMANCA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F37015856",
    via_tipo: null,
    via_nombre: "PUERTA DE ZAMORA",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "37005",
    direccion_poblacion: "SALAMANCA",
    direccion_provincia: "",
    banco_telefono: "923128600",
    banco_web: "WWW.CAJARURAL.COM/SALAMANCA",
    banco_nombre_comercial: "",
    cod_autonomia: "7",
    cod_lei: "95980020140005429655",
    banco_emails: ["atencionalcliente.3016@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3017",
    banco_nombre: "CAJA RURAL DE SORIA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F42001255",
    via_tipo: "CL",
    via_nombre: "DIPUTACION",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "42002",
    direccion_poblacion: "SORIA",
    direccion_provincia: "",
    banco_telefono: "975212840",
    banco_web: "WWW.RURALVIA.COM/SORIA",
    banco_nombre_comercial: "CAJA SORIA",
    cod_autonomia: "7",
    cod_lei: "95980020140005396966",
    banco_emails: ["atencioncliente.soria@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3018",
    banco_nombre:
      "CAJA RURAL REGIONAL SAN AGUSTIN FUENTE ALAMO MURCIA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F30603476",
    via_tipo: null,
    via_nombre: "GRAN VIA",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "30320",
    direccion_poblacion: "FUENTE ALAMO",
    direccion_provincia: "MURCIA",
    banco_telefono: "968597211",
    banco_web: "WWW.RURALREGIONAL.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "13",
    cod_lei: "95980020140005220038",
    banco_emails: ["info@ruralregional.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3020",
    banco_nombre:
      "CAJA RURAL DE UTRERA, SOCIEDAD COOPERATIVA ANDALUZA DE CREDITO",
    banco_cif: "F41016544",
    via_tipo: "PZ",
    via_nombre: "ALTOZANO",
    via_numero: "22",
    via_resto: "",
    direccion_cp: "41710",
    direccion_poblacion: "UTRERA",
    direccion_provincia: "SEVILLA",
    banco_telefono: "954862233",
    banco_web: "WWW.CAJARURAL.COM/UTRERA",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005219941",
    banco_emails: ["cr.utrera@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3023",
    banco_nombre: "CAJA RURAL DE GRANADA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F18009274",
    via_tipo: "AV",
    via_nombre: "DON BOSCO",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "18006",
    direccion_poblacion: "GRANADA",
    direccion_provincia: "",
    banco_telefono: "958242400",
    banco_web: "E-RURALGRANADA.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005220135",
    banco_emails: ["atencioncliente.crg@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3025",
    banco_nombre:
      "CAIXA DE CREDIT DELS ENGINYERS- CAJA DE CREDITO DE LOS INGENIEROS,  S. COOP. DE CREDITO",
    banco_cif: "F08216863",
    via_tipo: null,
    via_nombre: "VIA LAIETANA",
    via_numero: "39",
    via_resto: "",
    direccion_cp: "8003",
    direccion_poblacion: "BARCELONA",
    direccion_provincia: "",
    banco_telefono: "933106000",
    banco_web: "WWW.CAJA-INGENIEROS.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "9",
    cod_lei: "5493007RT80TMKY7TO30",
    banco_emails: ["grup@caixa-enginyers.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3029",
    banco_nombre:
      "CAJA DE CREDITO DE PETREL, CAJA RURAL, COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F03014982",
    via_tipo: "CL",
    via_nombre: "SAN BARTOLOME",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "3610",
    direccion_poblacion: "PETRER",
    direccion_provincia: "ALICANTE",
    banco_telefono: "966952780",
    banco_web: "www.grupocooperativocajamar.es/caixapetrer/es/comun/",
    banco_nombre_comercial: "CAIXAPETRER",
    cod_autonomia: "15",
    cod_lei: "635400AOYRRGOJUGAX32",
    banco_emails: ["caixapetrer@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3035",
    banco_nombre: "CAJA LABORAL POPULAR COOP. DE CREDITO",
    banco_cif: "F75076935",
    via_tipo: "PS",
    via_nombre: "JOSE MARIA ARIZMENDIARRIETA",
    via_numero: "S/N",
    via_resto: "",
    direccion_cp: "20500",
    direccion_poblacion: "MONDRAGON",
    direccion_provincia: "GIPUZKOA",
    banco_telefono: "943719500",
    banco_web: "WWW.CAJALABORAL.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "16",
    cod_lei: "549300G3C8M0WXQCWH61",
    banco_emails: ["servicio.de.atencion.al.cliente@laboralkutxa.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3045",
    banco_nombre: "CAIXA RURAL ALTEA, COOPERATIVA DE CREDIT VALENCIANA",
    banco_cif: "F03027901",
    via_tipo: "PZ",
    via_nombre: "DEL CONVENT",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "3590",
    direccion_poblacion: "ALTEA",
    direccion_provincia: "ALICANTE",
    banco_telefono: "965841350",
    banco_web: "www.grupocooperativocajamar.es/caixaltea/es/comun/",
    banco_nombre_comercial: "CAIXALTEA",
    cod_autonomia: "15",
    cod_lei: "635400AAPLXTJGKCMB39",
    banco_emails: ["caixaltea@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3058",
    banco_nombre: "CAJAMAR CAJA RURAL, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F04743175",
    via_tipo: "PZ",
    via_nombre: "PUERTA DE PURCHENA",
    via_numero: "10",
    via_resto: "",
    direccion_cp: "4001",
    direccion_poblacion: "ALMERIA",
    direccion_provincia: "",
    banco_telefono: "950210100",
    banco_web: "www.cajamar.es/es/comun/",
    banco_nombre_comercial: "CAJAMAR CAJA RURAL",
    cod_autonomia: "1",
    cod_lei: "635400CE9HHFB55PEY43",
    banco_emails: ["cajamar@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3059",
    banco_nombre: "CAJA RURAL DE ASTURIAS, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F33007337",
    via_tipo: "CL",
    via_nombre: "MELQUIADES ALVAREZ",
    via_numero: "7",
    via_resto: "",
    direccion_cp: "33002",
    direccion_poblacion: "OVIEDO",
    direccion_provincia: "ASTURIAS",
    banco_telefono: "985220591",
    banco_web: "WWW.RURALVIA.COM/ASTURIAS/",
    banco_nombre_comercial: "",
    cod_autonomia: "3",
    cod_lei: "95980020140005219553",
    banco_emails: ["servicioatencioncliente@crasturias.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3060",
    banco_nombre:
      "CAJA RURAL DE BURGOS, FUENTEPELAYO, SEGOVIA Y CASTELLDANS, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F40248791",
    via_tipo: "CL",
    via_nombre: "LOS COCHES",
    via_numero: "2-4",
    via_resto: "",
    direccion_cp: "40002",
    direccion_poblacion: "SEGOVIA",
    direccion_provincia: "",
    banco_telefono: "947257400",
    banco_web: "",
    banco_nombre_comercial: "CAJAVIVA",
    cod_autonomia: "7",
    cod_lei: "95980020140005485624",
    banco_emails: ["servicioatencioncliente@cajaviva.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3067",
    banco_nombre:
      "CAJA RURAL DE JAEN, BARCELONA Y MADRID, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F23009145",
    via_tipo: "CL",
    via_nombre: "EL CONDADO, MANZANA 23",
    via_numero: null,
    via_resto: "PQ. C. TECNO. GEOLIT",
    direccion_cp: "23620",
    direccion_poblacion: "MENGIBAR",
    direccion_provincia: "JAEN",
    banco_telefono: "953210100",
    banco_web: "WWW.RURALVIA.COM/JAEN",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005418403",
    banco_emails: ["cajarural@crjaen.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3070",
    banco_nombre:
      "CAIXA RURAL GALEGA, SOCIEDAD COOPERATIVA DE CREDITO LIMITADA GALLEGA",
    banco_cif: "F27005164",
    via_tipo: "AV",
    via_nombre: "MONTERO RIOS",
    via_numero: "24-26",
    via_resto: "",
    direccion_cp: "27002",
    direccion_poblacion: "LUGO",
    direccion_provincia: "",
    banco_telefono: "982280220",
    banco_web: "WWW.RURALVIA.COM/LUGO",
    banco_nombre_comercial: "",
    cod_autonomia: "11",
    cod_lei: "95980020140005488437",
    banco_emails: ["caixaruralgalega@caixaruralgalega.gal"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3076",
    banco_nombre: "CAJASIETE, CAJA RURAL, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F38005245",
    via_tipo: "AV",
    via_nombre: "MANUEL HERMOSO ROJAS",
    via_numero: "8",
    via_resto: "",
    direccion_cp: "38003",
    direccion_poblacion: "SANTA CRUZ DE TENERIFE",
    direccion_provincia: "TENERIFE",
    banco_telefono: "922608400",
    banco_web: "WWW.CAJASIETE.COM",
    banco_nombre_comercial: "CAJASIETE",
    cod_autonomia: "5",
    cod_lei: "95980020140005485333",
    banco_emails: ["cajasiete_sac@cajasiete.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3080",
    banco_nombre: "CAJA RURAL DE TERUEL, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F44002756",
    via_tipo: "PZ",
    via_nombre: "CARLOS CASTEL",
    via_numero: "14",
    via_resto: "",
    direccion_cp: "44001",
    direccion_poblacion: "TERUEL",
    direccion_provincia: "",
    banco_telefono: "978617100",
    banco_web: "WWW.CAJARURAL.COM/TERUEL/       HOME.HTML",
    banco_nombre_comercial: "",
    cod_autonomia: "2",
    cod_lei: "95980020140005417336",
    banco_emails: ["crteruel_defensa_cliente@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3081",
    banco_nombre: "EUROCAJA RURAL, SOCIEDAD COOPERATIVA DE CRÉDITO",
    banco_cif: "F45003993",
    via_tipo: "CL",
    via_nombre: "MEJICO",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "45004",
    direccion_poblacion: "TOLEDO",
    direccion_provincia: "",
    banco_telefono: "925269600",
    banco_web: "WWW.EUROCAJARURAL.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "8",
    cod_lei: "95980020140005552166",
    banco_emails: ["dpd@eurocajarural.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3085",
    banco_nombre: "CAJA RURAL DE ZAMORA, COOPERATIVA DE CREDITO",
    banco_cif: "F49002454",
    via_tipo: "AV",
    via_nombre: "ALFONSO IX",
    via_numero: "7",
    via_resto: "",
    direccion_cp: "49013",
    direccion_poblacion: "ZAMORA",
    direccion_provincia: "",
    banco_telefono: "980532671",
    banco_web: "WWW.CAJARURALDIGITAL.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "7",
    cod_lei: "95980020140005219844",
    banco_emails: ["atcliente.zamora@somoscajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3089",
    banco_nombre:
      "CAJA RURAL DE BAENA NTRA. SRA. DE GUADALUPE SOCIEDAD COOPERATIVA DE CREDITO ANDALUZA",
    banco_cif: "F14016166",
    via_tipo: "CL",
    via_nombre: "DUQUE DE RIVAS",
    via_numero: "3",
    via_resto: "",
    direccion_cp: "14850",
    direccion_poblacion: "BAENA",
    direccion_provincia: "CORDOBA",
    banco_telefono: "957670772",
    banco_web: "WWW.RURALVIA.COM/BAENA/",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005396869",
    banco_emails: ["baena@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3095",
    banco_nombre: "CAJA RURAL SAN ROQUE DE ALMENARA S. COOP. DE CREDITO V.",
    banco_cif: "F12013306",
    via_tipo: "CL",
    via_nombre: "DOCTOR BERENGUER",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "12590",
    direccion_poblacion: "ALMENARA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "962610054",
    banco_web: "www.grupocooperativocajamar.es/caixaruralalmenara/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400LATQHBDJVK2O07",
    banco_emails: ["caixaruralalmenara@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3096",
    banco_nombre:
      "CAIXA RURAL DE L'ALCUDIA, SOCIEDAD COOPERATIVA VALENCIANA DE  CREDITO",
    banco_cif: "F46043790",
    via_tipo: "AV",
    via_nombre: "VERGE DE L'ORETO",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "46250",
    direccion_poblacion: "L'ALCUDIA",
    direccion_provincia: "VALENCIA",
    banco_telefono: "962540166",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005551293",
    banco_emails: ["cliente_cralcudia@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3098",
    banco_nombre:
      "CAJA RURAL DE NUEVA CARTEYA,  SOCIEDAD COOPERATIVA ANDALUZA DE CREDITO",
    banco_cif: "F14011415",
    via_tipo: "AV",
    via_nombre: "ANDALUCIA",
    via_numero: "6",
    via_resto: "",
    direccion_cp: "14857",
    direccion_poblacion: "NUEVA CARTEYA",
    direccion_provincia: "CORDOBA",
    banco_telefono: "957678228",
    banco_web: "WWW.RURALVIA.COM/CARTEYA/",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005992740",
    banco_emails: ["ruralvia@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3102",
    banco_nombre:
      "CAIXA RURAL SANT VICENT FERRER DE LA VALL D'UIXO, COOP. DE CREDIT V.",
    banco_cif: "F12014221",
    via_tipo: "PZ",
    via_nombre: "CENTRO",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "12600",
    direccion_poblacion: "VALL DE UXO",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964663012",
    banco_web: "www.grupocooperativocajamar.es/caixasantvicent/es/comun/",
    banco_nombre_comercial: "C. SANT VICENT",
    cod_autonomia: "15",
    cod_lei: "635400NY7IQMBTTK4D30",
    banco_emails: ["caixasantvicent@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3104",
    banco_nombre:
      "CAJA RURAL DE CAÑETE DE LAS TORRES  NTRA.. SRA.DEL CAMPO SOCIEDAD COOPERATIVA ANDALUZA DE CREDITO",
    banco_cif: "F14011407",
    via_tipo: "PZ",
    via_nombre: "ESPAÑA",
    via_numero: "5",
    via_resto: "",
    direccion_cp: "14660",
    direccion_poblacion: "CAÑETE DE LAS TORRES",
    direccion_provincia: "CORDOBA",
    banco_telefono: "957183031",
    banco_web: "",
    banco_nombre_comercial: "C.R.CAÑETE",
    cod_autonomia: "1",
    cod_lei: "95980050FR4XC5F5QU23",
    banco_emails: ["canetedelastorres@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3105",
    banco_nombre:
      "CAIXA RURAL DE CALLOSA D'EN SARRIA, COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F03042595",
    via_tipo: "AV",
    via_nombre: "JAIME I",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "3510",
    direccion_poblacion: "CALLOSA D'EN SARRIA",
    direccion_provincia: "ALICANTE",
    banco_telefono: "965880058",
    banco_web: "www.grupocooperativocajamar.es/caixacallosa/es/comun/",
    banco_nombre_comercial: "CAIXACALLOSA",
    cod_autonomia: "15",
    cod_lei: "635400Q3SPCPIHXXGR35",
    banco_emails: ["caixacallosa@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3110",
    banco_nombre: "CAJA RURAL CATOLICO AGRARIA, S. COOP. DE CREDITO V.",
    banco_cif: "F12013223",
    via_tipo: "PZ",
    via_nombre: "MAYOR",
    via_numero: "10",
    via_resto: "",
    direccion_cp: "12540",
    direccion_poblacion: "VILLARREAL DE LOS INFANTES",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964520200",
    banco_web: "www.grupocooperativocajamar.es/caixaruralvila-real/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400T8P82JKHPUBD58",
    banco_emails: ["caixaruralvila-real@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3111",
    banco_nombre:
      "CAIXA RURAL LA VALL 'SAN ISIDRO', SOCIEDAD COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F12013207",
    via_tipo: "AV",
    via_nombre: "CORAZON DE JESUS",
    via_numero: "3",
    via_resto: "",
    direccion_cp: "12600",
    direccion_poblacion: "VALL DE UXO",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964697989",
    banco_web: "WWW.CAIXARURALLAVALL.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005651785",
    banco_emails: ["atencioncliente.3111@caixalavall.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3112",
    banco_nombre: "CAJA RURAL SAN JOSE DE BURRIANA, S. COOP. DE CREDITO V.",
    banco_cif: "F12013256",
    via_tipo: "PZ",
    via_nombre: "EL PLA",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "12530",
    direccion_poblacion: "BURRIANA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964510927",
    banco_web: "www.grupocooperativocajamar.es/caixaruralburriana/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400QRDROC5REDLP11",
    banco_emails: ["caixaruralburriana@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3113",
    banco_nombre: "CAJA RURAL SAN JOSE DE ALCORA S. COOP. DE CREDITO V.",
    banco_cif: "F12013272",
    via_tipo: "CL",
    via_nombre: "SAN FRANCISCO",
    via_numero: "14",
    via_resto: "",
    direccion_cp: "12110",
    direccion_poblacion: "ALCORA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964360976",
    banco_web: "WWW.RURALVIA.COM/ALCORA",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005485430",
    banco_emails: ["sac.alcora@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3115",
    banco_nombre:
      "CAJA RURAL 'NUESTRA MADRE DEL SOL', S. COOP. ANDALUZA DE CREDITO",
    banco_cif: "F14011399",
    via_tipo: "CL",
    via_nombre: "ALTO GUADALQUIVIR",
    via_numero: "4",
    via_resto: "",
    direccion_cp: "14430",
    direccion_poblacion: "ADAMUZ",
    direccion_provincia: "CORDOBA",
    banco_telefono: "957166028",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "959800STU2BCZ8XZG570",
    banco_emails: ["atencioncliente.madresol@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3117",
    banco_nombre: "CAIXA RURAL D'ALGEMESI, S. COOP. V. DE CREDIT",
    banco_cif: "F46043782",
    via_tipo: "CL",
    via_nombre: "SAN JOSE DE CALASANZ",
    via_numero: "6",
    via_resto: "",
    direccion_cp: "46680",
    direccion_poblacion: "ALGEMESI",
    direccion_provincia: "VALENCIA",
    banco_telefono: "962488030",
    banco_web: "WWW.CAJARURAL.COM/RURALES/3117",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005620357",
    banco_emails: ["atencioncliente.3117@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3118",
    banco_nombre: "CAIXA RURAL TORRENT COOPERATIVA DE CREDIT VALENCIANA",
    banco_cif: "F46047809",
    via_tipo: "AV",
    via_nombre: "AL VEDAT",
    via_numero: "3",
    via_resto: "",
    direccion_cp: "46900",
    direccion_poblacion: "TORRENT",
    direccion_provincia: "VALENCIA",
    banco_telefono: "961550054",
    banco_web: "www.grupocooperativocajamar.es/ruraltorrent/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400FTUWGNM6CHRI73",
    banco_emails: ["ruraltorrent@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3119",
    banco_nombre:
      "CAJA RURAL SAN JAIME DE ALQUERIAS NIÑO PERDIDO S. COOP. DE CREDITO V.",
    banco_cif: "F12013298",
    via_tipo: "CL",
    via_nombre: "JAIME CHICHARRO",
    via_numero: "24",
    via_resto: "",
    direccion_cp: "12539",
    direccion_poblacion: "ALQUERIAS NIÑO PERDIDO",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964591717",
    banco_web: "www.grupocooperativocajamar.es/caixalqueries/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400PG53OKXYYLRB68",
    banco_emails: ["caixalqueries@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3121",
    banco_nombre:
      "CAJA RURAL DE CHESTE, SOCIEDAD COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F46025433",
    via_tipo: "PZ",
    via_nombre: "DOCTOR CAJAL",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "46380",
    direccion_poblacion: "CHESTE",
    direccion_provincia: "VALENCIA",
    banco_telefono: "962515502",
    banco_web: "https://www.grupocooperativocajamar.es/crcheste/es/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400OVO6HWLUD2YY08",
    banco_emails: ["crcheste@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3123",
    banco_nombre: "CAIXA RURAL DE TURIS, COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F46027504",
    via_tipo: "PZ",
    via_nombre: "CONSTITUCION",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "46389",
    direccion_poblacion: "TURIS",
    direccion_provincia: "VALENCIA",
    banco_telefono: "962526061",
    banco_web: "www.grupocooperativocajamar.es/caixaturis/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "6354007ZW5CLO6YHGK36",
    banco_emails: ["caixaturis@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3127",
    banco_nombre:
      "CAJA RURAL DE CASAS IBAÑEZ, S. COOP. DE CREDITO DE CASTILLA-LA MANCHA",
    banco_cif: "F02004182",
    via_tipo: "CL",
    via_nombre: "TERCIA",
    via_numero: "49",
    via_resto: "",
    direccion_cp: "2200",
    direccion_poblacion: "CASAS IBAÑEZ",
    direccion_provincia: "ALBACETE",
    banco_telefono: "967460312",
    banco_web: "WWW.RURALVIA.COM/CASASIBANEZ",
    banco_nombre_comercial: "",
    cod_autonomia: "8",
    cod_lei: "95980020140005993904",
    banco_emails: ["servicioatencioncliente.casasibanez@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3130",
    banco_nombre: "CAJA RURAL SAN JOSE DE ALMASSORA, S. COOP. DE CREDITO V.",
    banco_cif: "F12013280",
    via_tipo: "CL",
    via_nombre: "TRINIDAD",
    via_numero: "20",
    via_resto: "",
    direccion_cp: "12550",
    direccion_poblacion: "ALMASSORA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964560003",
    banco_web: "WWW.TUCAJARURAL.COM",
    banco_nombre_comercial: "CAIXA ALMASSORA",
    cod_autonomia: "15",
    cod_lei: "95980020140005486594",
    banco_emails: ["info@caixalmassora.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3134",
    banco_nombre:
      "CAJA RURAL NUESTRA SEÑORA DE LA ESPERANZA DE ONDA, S. COOP. DE CREDITO V.",
    banco_cif: "F12013157",
    via_tipo: "PZ",
    via_nombre: "EL PLA",
    via_numero: "19",
    via_resto: "",
    direccion_cp: "12200",
    direccion_poblacion: "ONDA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964776677",
    banco_web: "WWW.RURALVIA.COM/ONDA",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005523939",
    banco_emails: ["caixa.onda@caixaonda.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3135",
    banco_nombre: "CAJA RURAL SAN JOSE DE NULES S. COOP. DE CREDITO V.",
    banco_cif: "F12013140",
    via_tipo: "CL",
    via_nombre: "MAYOR",
    via_numero: "66",
    via_resto: "",
    direccion_cp: "12520",
    direccion_poblacion: "NULES",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964656065",
    banco_web: "www.grupocooperativocajamar.es/caixaruralnules/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400T6AXCIH7EOTO46",
    banco_emails: ["caixaruralnules@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3138",
    banco_nombre: "RURALNOSTRA, SOCIEDAD COOPERATIVA DE CREDITO VALENCIANA",
    banco_cif: "F12013322",
    via_tipo: "CL",
    via_nombre: "DE TALES",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "12549",
    direccion_poblacion: "BETXI",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964623003",
    banco_web: "WWW.RURALNOSTRA.COM",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005310054",
    banco_emails: ["oficinescentrals@ruralnostra.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3140",
    banco_nombre: "CAJA RURAL DE GUISSONA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F25014754",
    via_tipo: "CL",
    via_nombre: "TRASPALAU",
    via_numero: "8",
    via_resto: "",
    direccion_cp: "25210",
    direccion_poblacion: "GUISSONA",
    direccion_provincia: "LLEIDA",
    banco_telefono: "973550248",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "9",
    cod_lei: "95980020140005925519",
    banco_emails: ["caixaguissona@caixaguissona.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3144",
    banco_nombre:
      "CAJA RURAL DE VILLAMALEA, S. COOP. DE CREDITO AGRARIO DE CASTILLA-LA MANCHA",
    banco_cif: "F02004299",
    via_tipo: "PZ",
    via_nombre: "DE LA CONCEPCION",
    via_numero: "1",
    via_resto: "",
    direccion_cp: "2270",
    direccion_poblacion: "VILLAMALEA",
    direccion_provincia: "ALBACETE",
    banco_telefono: "967483026",
    banco_web: "WWW.RURALVIA.COM/VILLAMALEA",
    banco_nombre_comercial: "",
    cod_autonomia: "8",
    cod_lei: "95980020140005977802",
    banco_emails: ["servicioatencioncliente.villamalea@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3150",
    banco_nombre: "CAJA RURAL DE ALBAL COOP. DE CREDITO V.",
    banco_cif: "F46043824",
    via_tipo: "PZ",
    via_nombre: "DEL JARDI",
    via_numero: "24",
    via_resto: "",
    direccion_cp: "46470",
    direccion_poblacion: "ALBAL",
    direccion_provincia: "VALENCIA",
    banco_telefono: "961260075",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005350406",
    banco_emails: ["albal@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3152",
    banco_nombre: "CAJA RURAL DE VILLAR, COOP. DE CREDITO V.",
    banco_cif: "F46043816",
    via_tipo: "CL",
    via_nombre: "LAS CRUCES",
    via_numero: "33",
    via_resto: "",
    direccion_cp: "46170",
    direccion_poblacion: "VILLAR DEL ARZOBISPO",
    direccion_provincia: "VALENCIA",
    banco_telefono: "961646034",
    banco_web: "www.grupocooperativocajamar.es/crvillar/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400TVFCZ8KWG6YZ06",
    banco_emails: ["crvillar@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3157",
    banco_nombre: "CAJA RURAL LA JUNQUERA DE CHILCHES, S. COOP. DE CREDITO V.",
    banco_cif: "F12013124",
    via_tipo: "PZ",
    via_nombre: "ESPAÑA",
    via_numero: "8",
    via_resto: "",
    direccion_cp: "12592",
    direccion_poblacion: "CHILCHES",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964590089",
    banco_web: "www.grupocooperativocajamar.es/caixaruraldexilxes/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400JGUDBXA9SJAT89",
    banco_emails: ["caixaruraldexilxes@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3159",
    banco_nombre: "CAIXA POPULAR-CAIXA RURAL, S. COOP. DE CREDITO V.",
    banco_cif: "F46090650",
    via_tipo: "AV",
    via_nombre: "JUAN DE LA CIERVA",
    via_numero: "9",
    via_resto: "",
    direccion_cp: "46980",
    direccion_poblacion: "PATERNA",
    direccion_provincia: "VALENCIA",
    banco_telefono: "961318282",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005480677",
    banco_emails: ["info@caixapopular.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3160",
    banco_nombre: "CAIXA RURAL SANT JOSEP DE VILAVELLA, S. COOP. DE CREDITO V.",
    banco_cif: "F12013231",
    via_tipo: "CL",
    via_nombre: "CUEVA SANTA",
    via_numero: "11",
    via_resto: "",
    direccion_cp: "12526",
    direccion_poblacion: "VILLAVIEJA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964678000",
    banco_web: "www.grupocooperativocajamar.es/caixaruralvilavella/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400J15IRJJXMI6M28",
    banco_emails: ["caixaruralvilavella@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3162",
    banco_nombre: "CAIXA RURAL BENICARLO, S. COOP. DE  CREDIT V.",
    banco_cif: "F12013348",
    via_tipo: "AV",
    via_nombre: "JOAN CARLES I",
    via_numero: "18",
    via_resto: "",
    direccion_cp: "12580",
    direccion_poblacion: "BENICARLO",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964474062",
    banco_web: "WWW.CAJARURAL.COM/BENICARLO",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005418791",
    banco_emails: ["sac@caixabenicarlo.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3165",
    banco_nombre: "CAJA RURAL SAN ISIDRO DE VILAFAMES  S. COOP. DE CREDITO V.",
    banco_cif: "F12013215",
    via_tipo: "AV",
    via_nombre: "BARCELO",
    via_numero: "6",
    via_resto: "",
    direccion_cp: "12192",
    direccion_poblacion: "VILAFAMES",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964329027",
    banco_web: "www.grupocooperativocajamar.es/caixaruralvilafames/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400GCLK5ZHSHH5B80",
    banco_emails: ["caixaruralvilafames@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3166",
    banco_nombre: "CAIXA RURAL LES COVES DE VINROMA, S. COOP. DE CREDIT V.",
    banco_cif: "F12013363",
    via_tipo: "CL",
    via_nombre: "SAN ANTONIO",
    via_numero: "27",
    via_resto: "",
    direccion_cp: "12185",
    direccion_poblacion: "LES COVES DE VINROMA",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964426050",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "95980020140005621036",
    banco_emails: ["atencióncliente@caixacoves.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3174",
    banco_nombre: "CAIXA RURAL VINAROS, S. COOP. DE CREDIT. V.",
    banco_cif: "F12013249",
    via_tipo: "CL",
    via_nombre: "SAN CRISTOBAL",
    via_numero: "19",
    via_resto: "",
    direccion_cp: "12500",
    direccion_poblacion: "VINAROS",
    direccion_provincia: "CASTELLON",
    banco_telefono: "964407280",
    banco_web: "WWW.RURALVIA.COM",
    banco_nombre_comercial: "CAIXA VINAROS",
    cod_autonomia: "15",
    cod_lei: "95980020140005382222",
    banco_emails: ["sac_vinaros@cajarural.com"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3179",
    banco_nombre:
      "CAJA RURAL DE ALGINET, SOCIEDAD COOPERATIVA CREDITO VALENCIANA",
    banco_cif: "F46163598",
    via_tipo: "CL",
    via_nombre: "VALENCIA",
    via_numero: "13",
    via_resto: "",
    direccion_cp: "46230",
    direccion_poblacion: "ALGINET",
    direccion_provincia: "VALENCIA",
    banco_telefono: "961750400",
    banco_web: "www.grupocooperativocajamar.es/caixaruralalginet/es/comun/",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: "635400AQCMGMEAGQB886",
    banco_emails: ["caixaruralalginet@grupocooperativocajamar.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3184",
    banco_nombre:
      "CAJA DE CREDITO DE ALCOY, COOPERATIVA DE CREDITO VALENCIANA (EN LIQUIDACION)",
    banco_cif: "F03285467",
    via_tipo: "CL",
    via_nombre: "SANTA ROSA",
    via_numero: "48",
    via_resto: "",
    direccion_cp: "3800",
    direccion_poblacion: "ALCOY",
    direccion_provincia: "ALICANTE",
    banco_telefono: "965525112",
    banco_web: "",
    banco_nombre_comercial: "",
    cod_autonomia: "15",
    cod_lei: null,
    banco_emails: [],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3187",
    banco_nombre: "CAJA RURAL DEL SUR, S. COOP. DE CREDITO",
    banco_cif: "F91119065",
    via_tipo: "CL",
    via_nombre: "MURILLO",
    via_numero: "2",
    via_resto: "",
    direccion_cp: "41001",
    direccion_poblacion: "SEVILLA",
    direccion_provincia: "",
    banco_telefono: "954599100",
    banco_web: "WWW.CAJARURALDELSUR.ES",
    banco_nombre_comercial: "",
    cod_autonomia: "1",
    cod_lei: "95980020140005375335",
    banco_emails: ["atencioncliente@crsur.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3190",
    banco_nombre:
      "CAJA RURAL DE ALBACETE, CIUDAD REAL Y CUENCA, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F45755220",
    via_tipo: "CL",
    via_nombre: "TESIFONTE GALLEGO",
    via_numero: "18",
    via_resto: "",
    direccion_cp: "2002",
    direccion_poblacion: "ALBACETE",
    direccion_provincia: "ALBACETE",
    banco_telefono: "925504224",
    banco_web: "WWW.GLOBALCAJA.ES",
    banco_nombre_comercial: "GLOBALCAJA",
    cod_autonomia: "8",
    cod_lei: "95980020140005484654",
    banco_emails: ["servicioatencioncliente@globalcaja.es"],
  },
  {
    banco_tipo: "CC",
    banco_codigo: "3191",
    banco_nombre: "CAJA RURAL DE ARAGON, SOCIEDAD COOPERATIVA DE CREDITO",
    banco_cif: "F99320848",
    via_tipo: "CL",
    via_nombre: "COSO",
    via_numero: "29",
    via_resto: "",
    direccion_cp: "50003",
    direccion_poblacion: "ZARAGOZA",
    direccion_provincia: "",
    banco_telefono: "976763300",
    banco_web: "",
    banco_nombre_comercial: "BANTIERRA",
    cod_autonomia: "2",
    cod_lei: "95980020140005012943",
    banco_emails: ["cajaruraldearagon@craragon.es"],
  },
];
